[package]
name = "snm_shim"
version = "0.0.1-104"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.1.0"
env_logger = "0.11.2"
snm_utils = { path = "../snm_utils" }
snm_config = { path = "../snm_config" }
snm_download_builder ={ path = "../snm_download_builder" }
snm_atom ={ path = "../snm_atom"}
color-backtrace = "0.6.1"
tracing = "0.1"
tracing-subscriber = "0.3"
