[package]
name = "snm_utils"
version = "0.0.1-89"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.58"
config = "0.14.0"
reqwest = { version = "0.12.3", features = ["stream", "native-tls-vendored"] }
serde_json = "1.0.114"
colored = "2.1.0"
termcolor = "1.4.1"
backtrace = "0.3.71"
