[package]
edition = "2021"
name    = "snm_utils"
version = "0.0.1-119"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow       = "1.0.75"
backtrace    = "0.3.71"
colored      = "2.1.0"
config       = "0.14.0"
dialoguer    = "0.11.0"
dunce        = { workspace = true }
flate2       = "1.0.28"
reqwest      = { workspace = true, features = ["stream", "native-tls-vendored"] }
semver       = { workspace = true }
serde_json   = "1.0.114"
tar          = "0.4.40"
termcolor    = "1.4.1"
thiserror    = "1.0.58"
wait-timeout = { workspace = true }
which        = { workspace = true }
xz2          = { version = "0.1.7", features = ["static"] }
zip          = "2.1.3"
dirs         = { workspace = true }
tracing      = { workspace = true }
tracing-subscriber = { workspace = true }
