[toolchain]
channel = "nightly-2025-01-11"
target = [
  "aarch64-apple-darwin", 
  "x86_64-apple-darwin",
  "aarch64-unknown-linux-gnu", 
  "x86_64-unknown-linux-gnu", 
  "aarch64-pc-windows-msvc", 
  "x86_64-pc-windows-msvc",
]
profile = "default"
