[package]
name = "snm_test_utils"
version = "0.1.0"
edition = "2024"

[dependencies]
tempfile = { workspace = true }
test-context = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
