name: Publish

inputs:
  tag_name:
    description: '发布的标签名称'
    required: true
  tag:
    description: '发布的标签名称'
    required: true

runs:
  using: "composite"
  steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4
    
    - name: Display structure of downloaded files
      shell: bash
      run: ls -R

    - name: Create Draft Release Upload Release Asset
      id: upload-release-asset
      uses: softprops/action-gh-release@v2
      # if: startsWith(inputs.tag_name, 'refs/tags/')
      with:
        tag_name: ${{ inputs.tag_name }}
        draft: true
        prerelease: false
        files: |
          **/*.tar.gz

    - name: Update Release
      # if: startsWith(inputs.tag_name, 'refs/tags/')
      shell: bash
      run: | 
        echo "Updating release..."
        gh release edit ${{ inputs.tag_name }} --draft=false --latest
