[package]
name = "snm_node_version"
version = "0.0.1-100"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snm_utils = { path = "../snm_utils" }
serde = { version = "1.0", features = ["derive"] }
