
[package]
name = "snm_config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.14.0"
serde = { version = "1.0", features = ["derive"] }
dirs = "5.0.1"
snm_npmrc = { path = "../snm_npmrc" }
snm_utils = { path = "../snm_utils" }
