
[package]
name = "snm_config"
version = "0.0.1-101"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.14.0"
serde = { version = "1.0", features = ["derive"] }
dirs = "5.0.1"
snm_npmrc = { path = "../snm_npmrc" }
snm_utils = { path = "../snm_utils" }
snm_package_json ={ path = "../snm_package_json"}
snm_node_version = { path = "../snm_node_version" }
