[package]
name = "dev-tools"
version = "0.0.1-117"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name='tools'
path="./src/main.rs"

[dependencies]
toml_edit = "0.22.14"
glob = "0.3.1"
semver = "1.0.23"
inquire = "0.7.5"
