name: canary-windows
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev 
jobs:

  setup:
    runs-on: windows-2019
    steps:
      - run: echo "setup environment"
        shell: bash
    outputs:
      target: x86_64-pc-windows-msvc
 
  run_test:
    runs-on: windows-2019
    needs: setup
    steps:

      - name: Test get environment variables
        run: |
          echo "target: ${{ needs.setup.outputs.target }}"
          echo "ttt: ${{ needs.setup.outputs.target }}"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
          target: ${{ needs.setup.outputs.target }}

      - name: Cargo testing
        run: |
            cargo t
        env:
          RUST_BACKTRACE: full

  run_build:
    runs-on: windows-2019
    needs: setup
    steps:

      - name: Test get environment variables
        run: |
          echo "target: ${{ needs.setup.outputs.target }}"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
          target: ${{ needs.setup.outputs.target }}

      - name: Build binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --release --target ${{ needs.setup.outputs.target }}

      - name: Build archive
        shell: bash
        run: |
          mkdir archive
          cp LICENSE README.md target/${{ env.TARGET }}/release/{node.exe,npm.exe,npx.exe,pnpm.exe,pnpx.exe} archive/
          7z a ${{ env.TARGET }}.7z archive/*
          ls -l

      - name: Calculate SHA256 checksum
        shell: bash
        run: |
          echo "Calculating SHA256 for ${{ needs.setup.outputs.target }}.tar.gz..."
          shasum -a 256 ${{ needs.setup.outputs.target }}.tar.gz | tee ${{ needs.setup.outputs.target }}.sha256
          cat ${{ needs.setup.outputs.target }}.sha256

      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: ${{ needs.setup.outputs.target }}.tar.gz
          path: ${{ needs.setup.outputs.target }}.tar.gz

      - name: Upload archive sha256
        uses: actions/upload-artifact@v4
        with:
          name: ${{ needs.setup.outputs.target }}.sha256
          path: ${{ needs.setup.outputs.target }}.sha256

 