name: canary-windows
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
jobs:
  build-windows:
    runs-on: windows-2019
    env:
      TARGET: x86_64-pc-windows-msvc
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ env.TARGET }}
      - name: Build binary
        run: |
          cargo build --verbose --release --target ${{ env.TARGET }}
        env:
          RUST_BACKTRACE: full
      - name: Build archive
        shell: bash
        run: |
          mkdir archive
          cp LICENSE README.md target/${{ env.TARGET }}/release/{node.exe,npm.exe,npx.exe,pnpm.exe,pnpx.exe} archive/
          7z a ${{ env.TARGET }}.7z archive/*
          ls -l
      - name: Upload archive
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.TARGET }}.7z
          path: ${{ env.TARGET }}.7z


