name: debug-install-shell

on:
  push:
    branches: [ "**" ]        # 监听所有分支的推送
  pull_request:
    branches: [ "**" ]        # 监听所有分支的 PR


jobs:
  unit-testing:
    name: Unit testing
    strategy:
      matrix:
        include:
            # Linux targets (GNU)
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu    # 64位 Linux (GNU)
          - os: ubuntu-latest
            target: i686-unknown-linux-gnu      # 32位 Linux (GNU)
            # Linux targets (MUSL)
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl   # 64位 Linux (MUSL)
          - os: ubuntu-latest
            target: i686-unknown-linux-musl     # 32位 Linux (MUSL)
          - os: macos-14
            target: aarch64-apple-darwin        # Apple Silicon Mac
          - os: macos-13
            target: x86_64-apple-darwin         # Intel Mac
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Tests install
        run: | 
          chmod +x install.sh
          ./install.sh
          if [ ! -d ~/.snm ]; then
            echo "Error: ~/.snm directory not found!"
            exit 1
          fi
          ls -l ~/.snm
        env:
          RUST_BACKTRACE: full
