name: DebugBuild

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Building
        uses: ./.github/workflows/build.yml
 