name: DebugBuild

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  test-building:
    name: Test building
    strategy:
      matrix:
        include:
            # Linux targets (GNU)
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu    # 64位 Linux (GNU)
            # Linux targets (MUSL)
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl   # 64位 Linux (MUSL)
            
            # Windows targets
          - os: windows-latest
            target: x86_64-pc-windows-msvc      # 64位 Windows (MSVC)
          - os: windows-latest
            target: x86_64-pc-windows-gnu       # 64位 Windows (MinGW)

            # macOS targets
          - os: macos-14
            target: aarch64-apple-darwin        # Apple Silicon Mac
          - os: macos-13
            target: x86_64-apple-darwin         # Intel Mac
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Install Dependencies
      #   if: matrix.os == 'ubuntu-latest'
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y openssl pkg-config libssl-dev musl-tools
      #     if [ "${{ matrix.target }}" = "x86_64-unknown-linux-musl" ]; then
      #       # 为 musl target 设置特殊的环境变量和依赖
      #       sudo apt-get install -y musl-tools
      #       echo "OPENSSL_DIR=/usr/include/openssl" >> $GITHUB_ENV
      #       echo "OPENSSL_LIB_DIR=/usr/lib/x86_64-linux-gnu" >> $GITHUB_ENV
      #     fi

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          override: true
          target: ${{ matrix.target }}

      # - name: Debug OpenSSL dependency
      #   if: matrix.os == 'ubuntu-latest' && matrix.target == 'x86_64-unknown-linux-musl'
      #   run: |
      #     cargo tree --target x86_64-unknown-linux-musl -i openssl-sys
      #     # 也可以检查所有依赖
      #     cargo tree --target x86_64-unknown-linux-musl | grep -i openssl

      - name: Build Binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --release --target ${{ matrix.target }}