name: DebugBuild

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  test-building:
    name: Cross-platform build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu    # 64位 Linux (GNU)
          - x86_64-unknown-linux-musl   # 64位 Linux (MUSL)
          - x86_64-pc-windows-msvc      # 64位 Windows (MSVC)
          - x86_64-pc-windows-gnu       # 64位 Windows (MinGW)
          - aarch64-apple-darwin        # Apple Silicon Mac
          - x86_64-apple-darwin         # Intel Mac
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          override: true
          target: ${{ matrix.target }}

      - name: Install cross
        uses: taiki-e/install-action@v2
        with:
          tool: cross

      - name: Build with cross
        run: cross build --verbose --release --target ${{ matrix.target }}