name: Bump Homebrew Formula

on:
  push:
    branches:
      - dev
    # paths:
    #   - 'Formula/snm.rb'

jobs:
  bump-formula:
    runs-on: ubuntu-latest

    steps:
      - name: Update Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          # Required, custom GitHub access token with the 'public_repo' and 'workflow' scopes
          token: ${{secrets.HOMEBREW_GITHUB_TOKEN}}
          # Optional, will commit with this user name
          user_name: ityuany
          # Optional, will commit with this user email
          user_email: 519495771@qq.com
          # Optional, will create tap repo fork in organization
          # org: ORG
          # Optional, use the origin repository instead of forking
          no_fork: false
          # Optional, defaults to homebrew/core
          tap: sheinsight/homebrew-shined
          # Formula name, required
          formula: snm
          # Optional, will be determined automatically
          # tag: ${{github.ref}}
          # # Optional, will be determined automatically
          # revision: ${{github.sha}}
          # # Optional, if don't want to check for already open PRs
          # force: false # true