name: Windows

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

env:
  RUST_BACKTRACE: full
  SNM_LOG: trace
  CI: true

jobs:
  unit-testing:
    name: Unit testing
    strategy:
      matrix:
        include:
            # Windows targets
          - os: windows-latest
            target: x86_64-pc-windows-msvc      # 64位 Windows (MSVC)
          - os: windows-latest
            target: i686-pc-windows-msvc        # 32位 Windows (MSVC)
          - os: windows-latest
            target: x86_64-pc-windows-gnu       # 64位 Windows (MinGW)
          - os: windows-latest
            target: i686-pc-windows-gnu         # 32位 Windows (MinGW)
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          override: true
          target: ${{ matrix.target }}

      - name: Run tests
        run: | 
          cargo install just
          just setup 
          cargo b --verbose
          just ci-e2e 